version: "3.9"
   
services:
  db:
    image: postgres
    ports:
      - "92.205.189.60:5432:5432"
    volumes:
      - ./database_folder/database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - container_network
    env_file:
      - db.env
  backend:
    image: container_backend
    build: ./backend
    volumes:
      - ./backend:/backend
      - ./uploads:/uploads
    ports:
      - "92.205.189.60:8080:8080"
    depends_on:
      - db
    networks:
      - container_network
  frontend:
    stdin_open: true
    image: container_frontend
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "92.205.189.60:3000:3000"
    depends_on:
      - db
    networks:
      - container_network
networks:
  container_network:
    driver: bridge
